---
title: "Notes"
output: html_notebook
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidytext); library(dplyr); library(gutenbergr); library(stringr)
library(tidyr)
```


```{r}

gutenberg_works() %>%
  filter(str_detect(author, 'Dante'))

```



```{r}
commedia <- 
  gutenberg_download(1004) %>%
  # Remove header and footer matter
  slice(269:19842) %>%
  # Number lines for reference
  mutate(line = row_number()) %>%
  unnest_tokens(word, text) %>%
  mutate(word = str_extract(word, "[a-z]+"))

commedia_afinn <-
  commedia %>%
  inner_join(get_sentiments("afinn")) %>% 
  #summarise(sentiment = sum(score)) %>% 
  mutate(method = "AFINN")

commedia_bing <-
  commedia %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

tst <-
  commedia %>%
  mutate(word_num = row_number()) %>%
  left_join(get_sentiments("nrc")) %>%
  mutate(is = !is.na(sentiment)) %>%
  group_by(gutenberg_id,line,word,word_num) %>%
  spread(sentiment, is) %>%
  select(gutenberg_id:trust) %>%
  left_join(get_sentiments("bing")) %>%
  left_join(get_sentiments("afinn"))
  
  
```

