---
title: "Primavera"
subtitle: "First green truths"
output: html_notebook
---

*...and morning came and showed Snow the prism hidden in his sharded heart.*  
*And Snow thought to himself: "How can one become light without embodying each color?"*

---

On earth we hold finches in our infant fingers,
we nibble from their beaks.

The grass is gold and so
is the ennameling.  

Planting our steps in cool alcoves, 
with bones of winter

Above the vaulted arches, crisscrossed, sing:
"You are forever entering" & "You are here"

we tilt the laden spoons of leaves
a hummingbird eucharist.

We could choke on the flowers
growing from our mouths.  

But it is spring and the blue wind cannot hold us.
Our wine resounds in delicate chalices

We tune our complicated instruments
at God's feet: harpischords and satellites.

A gaggle of angels tumbles out of hyperspace,
blasting their brass imperatives.

Why would we listen?

Our robes distilled
from poppies and coral cumulus

Leaves hued with chlorophyll and hope
of sun the branch wends toward, up

sky's pool of milkfire burns and births
we disappear into it brightly as the earth