## Away

Who knows how it came, Away? 
On high afar before the named things,

a shard of sky and since
what's touched was tinged with else.

Not only that.  Merely to learn
of absence was enough.

Holes fretted things
we thought we had: reflections, reveries.  

Re- and re-

In a tiny glass a room.
On a fish's head a cloud.
We found in others' eyes
a sun-lathed casements, ornamented skyline.

A world ever behind us.

The shard fell down
or sifted up from dirt-realms.

We tattooed its strangenesses into 
our flesh and called the distance longing.

In a soup-spoon we tasted hints
of sky, or no, the absence of 
castles.

We sat on park benches, 
luring birds closer for a scent of flight

We tried to destroy the Away
but obliterated it went aerosol.

It entered our clothes on clotheslines
(had there been clotheslines before?
How had we sent messages?  To whom?)

It rearranged the names in history books,
inserted episodes.

Asked about the ratio of away in airborne particulate matter,
scientists confer with psychiatrists.

Pharmaceutical conglomerates are testing the substance (the absence?)
Is it a sedative? A stimulant?
If we fall asleep here do we awake away?

Elevated concentrations have been found
in ticket stubs and cameras.

But this is anecdotal (from the Greek
'a nek', meaning unto death). Yet we suspect

All inky night some other shiny place
lures us through pinholes.

Limns us with its colors and its lines,
indistinguishable now from our (what is it to) own?

We needed a place to sing into.
