---
title: "Primavera"
subtitle: "First green truths"
output: html_notebook
---

*...and morning came and showed Snow the prism hidden in his sharded heart.*  
*And Snow thought to himself: "How can one become light without first embodying each color?"*

---

On earth we hold finches in our infant fingers,
we nibble from their beaks.

The grass is lacquered gold, with green ennameling.  

Planting our steps across cool alcoves, 
with bones of winter sycamore,

We have come to announce something to ourselves.

Above, the crisscrossed arches sing:
"You are forever entering" & "You are here"

This hummingbird eucharist, we tilt 
the laden spoons of leaves

We could choke on the flowers
growing from our mouths 

But it is spring and the blue wind cannot hold us.
Our wine resounds in delicate chalices

We tune our complicated instruments
at God's feet: harpischords and satellites.

A gaggle of angels tumbles out of hyperspace,
blasting their brass imperatives.

Why would we listen?

Our robes distilled
from poppies and coral cumulus

Leaves hued with chlorophyll and hope
of sun the branch wends 

up toward, to upward

sky's pool of milkfire burns and births
we disappear into it brightly as the earth

---

Truth and revision