---
title: "Nimbus B"
output: html_document
---

Behold the man, numb.  Pebbles I thumb,
bitumen and ribs.  Behold.
  
Blessed be blast and hubbub.
Blessed be notions enjambed.

Bless rabbits and burdock root
bedevilling the burbs' drab prefab.

Bamboozle businesses and lobbyists;
Bless me also thus:

biology's ad-lib, limbs ribboned with ebb of blood.

Bless us sunstabbed with each daybreak we absorb.
Bless blossoms born between the scree.

Bless this perception ... buffering...
bored by bright objects, bored straight through.

Bless any hub.  Bless you.

Bless belief gibbous past the brain.

Because it is Being we seek, we 
bow into ourselves, and then beyond.

Bless each obviously cribbed 
bequest I lob, each bursting symbol.

Billion-eyed observe me: above below backless

Become, behold and hold.


---



binary (there is only what is, and what is not.  Or rather, only what is.)
The average of being and non-being is becoming(?)

Beauties bent burnt

Bruise my flabby blabbering.

---

boss
bear
bring
bathe
born
breath
busy
blows
barge
both
Bright
Beatrice
Bid
Brings
blade
but
bye
beginning
body
bracelets
breaks
By
Being
broken
basalt
bough
brown
brought
blow
bright
bitterness
Broken
brothers
based
bride
Bored
bowels
BREACH
because
blazed
blind
Born
Behold
band
break
become
Beyond
beseech
boughs
bird
battled
behind
bid
benign
bent
Be
boundless
bitter
between
bound
bald
brazen
been
blades
bread
birdlet
Bear
bay
boast
birds
border
back
bow
believe
Bore
bending
barren
Battering
BOOK
blue
Black
Because
butt
Beheld
boles
breathe
besides
bit
beareth
BELATED
bad
bounden
booty
Bob
Bah
being
Ben
bourgeoning
by
bands
Bidding
better
bare
ballad
bold
bordering
bowed
Benjamin
big
borrowed
burst
Burnishing
Beauty
be
best
blown
beget
butt
begs
bade
Behind
Blowing
beneath
behold
But
brows
bell
bustling
BUT
beard
burthen
Belated
borne
beloved
battle
Ballad
barrel
before

Blab
bulb
blob
bobbing
bulbous
scabbed
scabbard
balm
swab
barbed
blood, hemoglobin
body, blood, brains, 
Malabar
bamboo
Bumblebee

---

double b:
scrubbird
red-dabbled
dribblers
dubbings
wibble-wobble
shibboleth
rubbish
bescribbled
squabbled
blubber
land-lubber
nobbier
hobbyist
blobbiness
crabbiness
bubbling
kabbalah
Hobbes
beslobber
rabble-rousing
scabbard
smooth-rubbed
lobbing
cribbings
webbing
clabber
squabble
cobble-stone
snubbing
cabbage
clobbering
hobbling
jibber
scribble
knobbed
dubbed
hobblebush
slobbery
flibbertigibbety
sobbing
chubby
shrubbery
quibbler
stubborn
rubbish
scrubbed
scrabbly
bobbing
abbreviated
scribblers
hobnobbed
gobbledygook
obbligato
sabbaths
throbbing
shabby
rubbings
nibblers
hobbled
grabbing
flabby
dribbling
blabbered
scabbing
blabbermouths
fibbed
flabbergasts
robbery
blabbermouth
globbier

---

End words:
grub
orb
undertub
deaf-dumb
crib
garb
plumb
slab
dab
bulb
intomb
web
lob
enjamb
scrub
Beelzebub
shrub
herb
hobnob
Skylab
nabob
carib
thingumbob
spider-crab
divebomb
ebb
bathtub
a-throb
numb
Sennacherib
bomb
windslab
jib
iamb
ahab
exurb
Pan-Arab
honeyblob
kerb
moneygrub
gab
absorb
blowjob
backstab
disturb
corn-cob
gob
wonder-dumb
vocab
scab
backcomb
prefab
rhumb
archsnob
catacomb
overdub
collab
coxcomb
climb
celeb
numb
overplumb
begob
proverb
dithyramb
blab
Maghreb
baobab
cherub
climb
comb
corymb
stubb
washtub
cob
womb
rehab
glib
death's-herb
Swab
bob
flab
rhubarb
kabob
pattern-bomb
funnel-web
doorjamb
perverb
doorknob
flub
plomb
woodgrub
lightbulb
enwomb
honeycomb
Aurangzeb
sub
disturb
entomb
drib
verb
succumb
